### PR TITLE
Remove superfluous

### PR DESCRIPTION
**Pull request by komashchenko**
No more SourceScramble and gamedata needed

### CODE REVIEW

**Comment by emrahkaraduman** [comment]
The plugin is really good, thank you. But I have a request. 30 seconds after a new round start, I want the command to be not accessible. Just like kgns does it.

**Comment by quasemago** [comment]
Thanks, but could you use the same code style as the rest of the plugin?

**Comment by komashchenko** [comment]
This is just an example of what can be done, you can remake the ego as you need

**Comment by quasemago** [comment]
Thanks, i will think about that.

**Pull request closed without merging**
